config/routes.rb
Rails.application.routes.draw do
  root 'home/home#index'
  
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  get 'logout' => 'user_sessions#destroy', :as => :logout
  post 'logout' => 'user_sessions#destroy'
  
  get 'login_signup' =>'user_sessions#login_signup'
  get 'login_partial' =>'user_sessions#login_partial'
  get 'signup_partial' => 'user_sessions#signup_partial'

  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

namespace :p5 do
  resources :sketches, only: [:show, :index]
end

scope path: '/notes', controller: 'notes/notes', as: 'notes' do
  get '/', action: 'index'
  # get '/:id', action: 'show', as: 'note'
  post '/', action: 'create'
  patch '/:id', action: 'update', as: 'update'
  get 'new', action: 'new'
  get ':id/edit', action: 'edit', as: 'edit'
  put ':id', action: 'update'
  delete ':id', action: 'destroy', as: 'destroy'
end

  # get '/p5', to: 'p5#index'
  get 'p5/update', to: 'p5#update', as: 'update_p5'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  self.table_name = 'na_notes'

  # broadcasts_to ->(notes) { "notes" }, inserts_by: :prepend
  broadcasts_refreshes

  #  after_update_commit :broadcast_update_later

  # private
  #   def broadcast_update_later
  #     broadcast_render_later_to 'notes', partial: 'notes', locals: { note: self }
  #   end
end

app/controllers/notes/notes_controller.rb
module Notes
  class NotesController < ApplicationController
    before_action :set_note, only: %i[ show edit update destroy ]

    # GET /notes or /notes.json
    def index
      @notes = Note.all.order(created_at: :desc)
    end

    # GET /notes/1 or /notes/1.json
    def show
    end

    # GET /notes/new
    def new
      @note = Note.new
    end

    # GET /notes/1/edit
    def edit
    end

    # POST /notes or /notes.json 
    def create
      @note = Note.new(note_params)
      @note.user = current_user;
        
       if current_user.nil?
        throw new Error("You must be logged in to create messages");
      end

      # binding.pry;

      respond_to do |format|
        if @note.save
          flash[:notice] = "Note created!"
          # format.html { render partial: 'new', notice: 'Note was successfully created.' }
          format.html {redirect_to notes_path, notice: 'Note was successfully created.'}
          format.turbo_stream
          format.json { render :show, status: :created, location: @note }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @note.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /notes/1 or /notes/1.json
    def update
      respond_to do |format|
        if @note.update(note_params)
          format.turbo_stream
          format.html { redirect_to notes_path, notice: 'Note was successfully created.' }
          format.json { render :show, status: :ok, location: @note }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @note.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /notes/1 or /notes/1.json
    def destroy
      # binding.pry
      @note.destroy!

      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_note
        @note = Note.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def note_params
        params.require(:note).permit(:title, :body)
      end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/notes/_empty_state.html.erb
<% if notes.none? %>
  <div class="empty-state empty-state--only-child">
    <p class="empty-state__text">
      You don't have any notes yet!
    </p>

    <%= render partial: 'new', local:{note: Note.new} %>
  </div>
<% end %>

app/views/notes/notes/_form.html.erb
<%= turbo_frame_tag @note do %>
  <%= form_with(model: @note, url: @note.new_record? ? notes_path : notes_update_path(@note), data: { turbo_frame: @note.new_record? ? 'new_note' : dom_id(@note) }) do |form| %>
    <% if @note.errors.any? %>
      <div style="color: red">
        <h2>
          <%= pluralize(@note.errors.count, "error" ) %> prohibited this note from being saved:
        </h2>
        <ul>
          <% @note.errors.each do |error| %>
            <li>
              <%= error.full_message %>
            </li>
            <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= form.label :title, style: "display: block" %>
        <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :body, style: "display: block" %>
        <%= form.text_field :body %>
    </div>
    <div>
      <%= form.submit class: "button is-primary"%>
    </div>
    <div>
      <%= link_to 'Back' , notes_path, data: {turbo_action: 'replace' , turbo_frame: 'main_page' }, class:"button is-light"
        %>
    </div>
  <% end %>
<% end %>

app/views/notes/notes/_new.html.erb
<%= turbo_frame_tag 'new_note' do %>
  <%= link_to "New Note" , notes_new_path, class: "button is-primary" , data: { turbo_frame: dom_id(Note.new) } %>
<% end %>

app/views/notes/notes/_note.html.erb
<%= turbo_stream_from note %>
<%= turbo_frame_tag note do %>
  <div class="box">
    <p>
      <strong>Title:</strong>
      <%= note.title %>
    </p>

    <p>
      <strong>Body:</strong>
      <%= note.body %>
    </p>
   <div class="field is-grouped">
      <p class="control m-0 p-0">
        <%= link_to "Edit", notes_edit_path(note), class: "button is-warning" %>
      </p>
      <p class="control m-0 p-0">
        <%= button_to "Delete", notes_destroy_path(note), method: :delete, class: "button is-danger" %>
      </p>
    </div> 
  </div>
<% end %>

app/views/notes/notes/create.turbo_stream.erb
<%= turbo_stream.prepend('notes', partial: 'note', locals:{note: @note}) %>
<%= turbo_stream.replace('new_note', partial: 'new') %>

app/views/notes/notes/destroy.turbo_stream.erb
<%= turbo_stream.remove @note %>

app/views/notes/notes/edit.html.erb
<h1>Editing note</h1>

<%= render "form" , note: @note %>

  <br>

  <div>
    <%= link_to "Show this note" , notes_path(@note) %> |
      <%= link_to "Back to notes" , notes_path %>
  </div>

app/views/notes/notes/index.html.erb
<%= turbo_frame_tag 'main_page' do %>
  <div class="container">
    <div class="header">
      <h1 class="title is-2">Notes</h1>
      <% unless @notes.empty? %>
        <%= render partial: 'new' %>
      <% end %>
    </div>
  </div>
  <%= render partial: 'empty_state', locals: { notes: @notes} %>
<% end %>
<%= turbo_stream_from 'notes' %>
<div id='notes'>
  <% @notes.each do |note| %>
    <%= render partial: 'note', locals: {note: note} %>
  <% end %>
</div>

app/views/notes/notes/new.html.erb
<h1>New note</h1>
<%= turbo_frame_tag 'new_note' do %>
  <%= render "form" , note: @note %>
    <% end %>

app/views/notes/notes/show.html.erb
<p style="color: green">
  <%= notice %>
</p>

<%= render @note %>

  <div>
    <%= link_to "Edit this note" , notes_edit_path(@note) %> |
      <%= link_to "Back to notes" , notes_path %>

        <%= button_to "Destroy this note" , @note, method: :delete %>
  </div>

app/views/notes/notes/update.turbo_stream.erb
<%= turbo_stream.replace( @note, partial: "note", locals:{note: @note}) %>