config/routes.rb
Rails.application.routes.draw do
  root 'home/home#index'
  
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  get 'logout' => 'user_sessions#destroy', :as => :logout
  post 'logout' => 'user_sessions#destroy'
  
  get 'login_signup' =>'user_sessions#login_signup'
  get 'login_partial' =>'user_sessions#login_partial'
  get 'signup_partial' => 'user_sessions#signup_partial'

  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

namespace :p5 do
  resources :sketches, only: [:show, :index]
end

scope path: '/notes', controller: 'notes/notes', as: 'notes' do
  get '/', action: 'index'
  # get '/:id', action: 'show', as: 'note'
  post '/', action: 'create'
  patch '/:id', action: 'update', as: 'update'
  get 'new', action: 'new'
  get ':id/edit', action: 'edit', as: 'edit'
  put ':id', action: 'update'
  delete ':id', action: 'destroy', as: 'destroy'
end

  # get '/p5', to: 'p5#index'
  get 'p5/update', to: 'p5#update', as: 'update_p5'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/user_sessions_controller.rb
# app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  # skip_before_action :require_login, only: [:new, :create]

    def new
    session[:return_to] ||= request.referer
  end

  def create
    @user = login(params[:email], params[:password])

    if @user
      session[:user_id] = @user.id
      flash[:notice] = 'Login successful'
      render partial: 'user_sessions/login&signup'
    else
      flash.now[:alert] = 'Login failed'
      render :new
    end
  end

  def login_signup
    render partial: 'user_sessions/login&signup'
  end

  
  def login_partial
    render partial: 'user_sessions/form'
  end

  def signup_partial
    @user = User.new 
    render partial: 'users/form', locals: { user: @user }
  end

  def destroy
    logout
    flash[:notice] = 'Login successful'
    render partial: 'user_sessions/login&signup'
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= turbo_frame_tag 'login/signup' do %> 
  <%= form_with url: login_path, method: :post do |f| %>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="actions pb-1">
      <%= f.submit "Login", class: 'button is-primary' %>
      <%= link_to 'Cancel', login_signup_path, class: 'button is-info', data: { turbo_action: 'replace', turbo_frame: 'frame_id' } %>
    </div>
  <% end %>
<% end %>

app/views/user_sessions/_login&signup.html.erb
<%= turbo_frame_tag 'login/signup' do %>
  <% if current_user %>
    Logged in as <%= current_user.email %>
    <%= link_to 'Logout', logout_path, method: :post %>
  <% else %>
  <section>
    <div class="columns is-multiline">
      <div class="column is-full pb-0">
        <%= link_to 'Login', login_partial_path %>
      </div>
      <div class="column is-full pt-0">
        <%= link_to 'Sign up', signup_partial_path %>
      </div>
    </div>
  </section>
  <% end %>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>