config/routes.rb
Rails.application.routes.draw do
  root 'home/home#index'
  
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  get 'logout' => 'user_sessions#destroy', :as => :logout
  post 'logout' => 'user_sessions#destroy'
  
  get 'login_signup' =>'user_sessions#login_signup'
  get 'login_partial' =>'user_sessions#login_partial'
  get 'signup_partial' => 'user_sessions#signup_partial'

  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

namespace :p5 do
  resources :sketches, only: [:show, :index]
end

scope path: '/notes', controller: 'notes/notes', as: 'notes' do
  get '/', action: 'index'
  # get '/:id', action: 'show', as: 'note'
  post '/', action: 'create'
  patch '/:id', action: 'update', as: 'update'
  get 'new', action: 'new'
  get ':id/edit', action: 'edit', as: 'edit'
  put ':id', action: 'update'
  delete ':id', action: 'destroy', as: 'destroy'
end

  # get '/p5', to: 'p5#index'
  get 'p5/update', to: 'p5#update', as: 'update_p5'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_navbar.html.erb
<div class="navbar-brand">
  <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
    <span aria-hidden="true"></span>
    <span aria-hidden="true"></span>
    <span aria-hidden="true"></span>
  </a>
</div>

<div id="navbarBasicExample" class="navbar-menu">
  <div class="navbar-start">
    <%= link_to 'Home', root_path, data: { turbo_action: 'replace', turbo_frame: 'main_page' }, class: 'navbar-item' %>
    <%= link_to 'p5 Sketches', p5_sketches_path, data: { turbo_action: 'replace', turbo_frame: 'main_page' }, class: 'navbar-item' %>
    <%= link_to 'Notes', notes_path, data: { turbo_action: 'replace', turbo_frame: 'main_page' }, class: 'navbar-item' %>
    <%= link_to 'Github Profile', 'https://github.com/kquizz', class: 'navbar-item' %>
  </div>
  <div class="navbar-end">
    <div class="navbar-item dark-link">
      <%= render 'user_sessions/login&signup' %>
    </div>
  </div>
</div>
<script>
  document.addEventListener('DOMContentLoaded', () => {
    const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
    if ($navbarBurgers.length > 0) {
      $navbarBurgers.forEach(el => {
        el.addEventListener('click', () => {
          const target = el.dataset.target;
          const $target = document.getElementById(target);
          el.classList.toggle('is-active');
          $target.classList.toggle('is-active');
        });
      });
    }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kquizz Portfolio</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <%= javascript_importmap_tags %>
  <%= turbo_refreshes_with method: :morph, scroll: :preserve %>
</head>
<body>
  <header class="header">
    <div class="container">
      <h1 class="title is-4 has-text-centered mt-4">Kquizz's Portfolio</h1>
    </div>
    <nav class="navbar is-primary mt-2" role="navigation" aria-label="main navigation">
      <%= render 'layouts/navbar' %>
    </nav>
  </header>
  <%= yield %>
</body>
</html>